### ISSUE TITLE
Setup of ultrasphinx for Gitorious is Failing

### ISSUE THREAD

**Issue by hoshposh** [rosenfeld/gitorious-cookbooks#21]
Trying the install steps on debian 6.0.5, and the chef script gets to the point where it has output the following:

**[2012-07-22T12:54:35+00:00] INFO: Processing script[setup ultrasphinx for Gitorious] action run (gitorious::default line 144)**

At this point I receive an error stating that _"chown: cannot access `config/ultrasphinx/production.conf': No such file or directory"_

**The full output is as follows:**
[2012-07-22T12:54:35+00:00] INFO: Processing script[setup ultrasphinx for Gitorious] action run (gitorious::default line 144)
(in /var/www/gitorious)
/usr/lib/aspell
(in /var/www/gitorious)
[2012-07-22T12:54:37+00:00] ERROR: script[setup ultrasphinx for Gitorious](gitorious::default line 144) has had an error
[2012-07-22T12:54:37+00:00] ERROR: script[setup ultrasphinx for Gitorious](/root/chef-solo/cookbooks/gitorious/recipes/default.rb:144:in `from_file') had an error:
script[setup ultrasphinx for Gitorious](gitorious::default line 144) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of "bash"  "/tmp/chef-script20120722-22133-1g9spkg-0" ----
STDOUT: (in /var/www/gitorious)
/usr/lib/aspell
(in /var/www/gitorious)
STDERR: rake aborted!
uninitialized constant ActiveSupport::Dependencies::Mutex
/var/www/gitorious/Rakefile:10:in `require'
(See full trace by running task with --trace)
rake aborted!
uninitialized constant ActiveSupport::Dependencies::Mutex
/var/www/gitorious/Rakefile:10:in`require'
(See full trace by running task with --trace)
chown: cannot access `config/ultrasphinx/production.conf': No such file or directory
---- End output of "bash"  "/tmp/chef-script20120722-22133-1g9spkg-0" ----
Ran "bash"  "/tmp/chef-script20120722-22133-1g9spkg-0" returned 1
/usr/lib/ruby/gems/1.8/gems/mixlib-shellout-1.0.0/lib/mixlib/shellout.rb:242:in`invalid!'
/usr/lib/ruby/gems/1.8/gems/mixlib-shellout-1.0.0/lib/mixlib/shellout.rb:228:in `error!'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/mixin/shell_out.rb:36:in`shell_out!'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/provider/execute.rb:58:in `action_run'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/provider/script.rb:33:in`action_run'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource.rb:454:in `send'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource.rb:454:in`run_action'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/runner.rb:49:in `run_action'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/runner.rb:85:in`converge'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/runner.rb:85:in `each'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/runner.rb:85:in`converge'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource_collection.rb:94:in `execute_each_resource'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in`call'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource_collection/stepable_iterator.rb:85:in`step'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource_collection/stepable_iterator.rb:55:in`each_with_index'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/resource_collection.rb:92:in `execute_each_resource'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/runner.rb:80:in`converge'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/client.rb:330:in `converge'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/client.rb:163:in`run'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/application/solo.rb:207:in `run_application'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/application/solo.rb:195:in`loop'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/application/solo.rb:195:in `run_application'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/../lib/chef/application.rb:70:in`run'
/usr/lib/ruby/gems/1.8/gems/chef-10.12.0/bin/chef-solo:25
/usr/bin/chef-solo:19:in `load'
/usr/bin/chef-solo:19
[2012-07-22T12:54:37+00:00] ERROR: Running exception handlers
[2012-07-22T12:54:37+00:00] ERROR: Exception handlers complete
[2012-07-22T12:54:37+00:00] FATAL: Stacktrace dumped to /root/chef-solo/chef-stacktrace.out
[2012-07-22T12:54:37+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: script[setup ultrasphinx for Gitorious] (gitorious::default line 144) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of "bash"  "/tmp/chef-script20120722-22133-1g9spkg-0" ----
STDOUT: (in /var/www/gitorious)
/usr/lib/aspell
(in /var/www/gitorious)
STDERR: rake aborted!
uninitialized constant ActiveSupport::Dependencies::Mutex
/var/www/gitorious/Rakefile:10:in`require'
(See full trace by running task with --trace)
rake aborted!
uninitialized constant ActiveSupport::Dependencies::Mutex
/var/www/gitorious/Rakefile:10:in `require'
(See full trace by running task with --trace)
chown: cannot access`config/ultrasphinx/production.conf': No such file or directory
---- End output of "bash"  "/tmp/chef-script20120722-22133-1g9spkg-0" ----
Ran "bash"  "/tmp/chef-script20120722-22133-1g9spkg-0" returned 1

**Comment by rosenfeld** [comment]
It seems you're using RubyGems 1.8 instead of strictly following the instructions in README. We don't support any other instructions than those.

**Comment by hoshposh** [comment]
Ahh, thanks for the pointer. I will review that part of the instructions
and correct my vagrant box accordingly.

Cheers,
Lyndon

**Comment by rosenfeld** [comment]
No problem :)
