### ISSUE TITLE
Error executing action `install` on resource 'gem_package[passenger]'

### ISSUE THREAD

**Issue by planestraveler** [rosenfeld/gitorious-cookbooks#26]
Here is a copy paste of the issue I have with the cookbook. 

Using a fresh Debian stable install.

I've tried to manually install the gem passenger and it did without issue.

An other note, I'm behind a proxy server

------- snip from the console log -----

```
[2012-11-19T11:37:15-05:00] INFO: Processing gem_package[passenger] action install (passenger_apache2::default line 43)

================================================================================
Error executing action `install` on resource 'gem_package[passenger]'
================================================================================

NoMethodError
-------------
undefined method `runtime_dependencies' for nil:NilClass

Resource Declaration:
---------------------
# In /root/chef-solo/cookbooks/passenger_apache2/recipes/default.rb

 43: gem_package "passenger" do
 44:   version node[:passenger][:version]
 45: end
 46:

Compiled Resource:
------------------
# Declared in /root/chef-solo/cookbooks/passenger_apache2/recipes/default.rb:43:in `from_file'

gem_package("passenger") do
  package_name "passenger"
  provider Chef::Provider::Package::Rubygems
  recipe_name "default"
  action :install
  version "3.0.14"
  retry_delay 2
  cookbook_name :passenger_apache2
  retries 0
end

[2012-11-19T11:37:15-05:00] ERROR: Running exception handlers
[2012-11-19T11:37:15-05:00] ERROR: Exception handlers complete
[2012-11-19T11:37:15-05:00] FATAL: Stacktrace dumped to /root/chef-solo/chef-stacktrace.out
[2012-11-19T11:37:15-05:00] FATAL: NoMethodError: gem_package[passenger] (passenger_apache2::default line 43) had an error: NoMethodError: undefined method `runtime_dependencies' for nil:NilClass
```

**Comment by rosenfeld** [comment]
What happens if you re-run chef-solo? What is your rubygems version (gem -v)? When you installed passenger gem manually, what version did you install? 3.0.14 (gem install -v 3.0.14 passenger)?

**Comment by rosenfeld** [comment]
Also notice that you can opt for another passenger version: https://raw.github.com/gist/847256/chef-gitorious-node-debian.json

**Comment by planestraveler** [comment]
Gem version is 1.4.2 (gem -v)

gem install -v 3.0.14 --http-proxy=myproxy.com
work successful install

With that chef-solo seem to work and continue it's operation..

Forcing the install of the specific version seem to have worked.

I've also put my proxy configuration in the /etc/chef/solo.rb for chef to use it when possible.

**Comment by planestraveler** [comment]
I had an other proxy problem at the step of making a clone of the gitourious repository

**Comment by rosenfeld** [comment]
I see. I never tried to use this recipe behind a proxied environment. I'm not willing to put much effort on this recipe at this moment, specially because I'm not using Gitorious myself for a long time. But if you send me a pull request with changes to support a proxy set-up I'll gladly merge. I should notice that I still watch Gitorious development sometimes and I know that they recently upgraded to latest Rails 2 and Rails 3 is on the way.

That means this recipe could be much simplified to use latest RubyGems (or the one available by default on Debian).

If you implement any of those changes (the latest one should be really simple) and is willing to maintain this project I can give you commit access to this repository if you want.

**Comment by planestraveler** [comment]
problem solved by putting the right proxy in env http_proxy and https_proxy.

**Comment by rosenfeld** [comment]
Would you mind to update the Wiki with the instructions above for how to set up Gitorious using this recipe when behind an HTTP proxy?

**Comment by kareiva** [comment]
:+1: to the above
