### ISSUE TITLE
Installations is aborted because passenger cannot be found

### ISSUE THREAD

**Issue by benjaminmateev** [rosenfeld/gitorious-cookbooks#6]
Here is the stacktrace

[Thu, 14 Jul 2011 08:20:28 +0000] INFO: execute[passenger-install-apache2-module -a] sh(passenger-install-apache2-module -a)
[Thu, 14 Jul 2011 08:20:28 +0000] ERROR: execute[passenger-install-apache2-module -a](passenger_apache2::default line 47) has had an error
[Thu, 14 Jul 2011 08:20:28 +0000] ERROR: Running exception handlers
[Thu, 14 Jul 2011 08:20:28 +0000] ERROR: Exception handlers complete
[Thu, 14 Jul 2011 08:20:28 +0000] FATAL: Stacktrace dumped to /root/chef-solo/chef-stacktrace.out
[Thu, 14 Jul 2011 08:20:28 +0000] FATAL: Errno::ENOENT: execute[passenger-install-apache2-module -a](passenger_apache2::default line 47) had an error: No such file or directory - passenger-install-apache2-module -a

**Comment by benjaminmateev** [comment]
The module is installed but not linked to /usr/bin somehow or /var/lib/gems1.8/bin is not in PATH, dont know whether this is a local issue on my version or a general one

**Comment by rosenfeld** [comment]
Hi benjamin, I've just followed the instructions in README in a fresh Debian 6.0.1 system and it finished after 12 minutes without any problems... Sorry, I couldn't replicate your problem. Are you running this recipe on a recent Debian system? Some have also installed it successfully in a recent Ubuntu distribution too.

**Comment by benjaminmateev** [comment]
Hey,

maybe it is because I am using Debian 6.0.3 But I reproduced it twice on a clean Debian 6.0.3 VM. Maybe on a side note, it is a OpenVZ VM but I dont think that this could be playing into this error.

I will try once again!

Thanks

**Comment by rosenfeld** [comment]
Hi, I'm a bit in a hurry because I'm moving to another company, and I'm traveling today for a week due to this change. When things get slower I'll download Debian 6.0.3 and try it again...

Good luck!

Cheers!

**Comment by karameloso** [comment]
@benjaminmateev, I had the same problem as you describe. I just opened a new terminal trying to "updatedb" & "locate" the passenger-install-apache2-module. Before I did anything else, I ran the chef-solo again and it just worked...

@Rosenfeld thanks for your nice tutorial! It helped a lot! ;)

**Comment by rosenfeld** [comment]
You're welcome @karameloso :) I'll try to do a full installation again this weekend on latest Debian.

**Comment by rosenfeld** [comment]
I've just reinstalled Gitorious with this recipe on latest Debian CD image and didn't have any problems...

**Comment by andreaswolf** [comment]
I had the same problem on a freshly installed Debian 6.0.2 - after manually executing `/var/lib/gems/1.8/gems/passenger-3.0.7/bin/passenger-install-apache2-module -a` it went like a charm. I experience this problem from time to time when using Ruby (I'm no Ruby coder, so I have no deeper knowledge of the whole system). Maybe it would help to run `updatedb` as @karameloso mentioned?

**Comment by rosenfeld** [comment]
I don't understand how updatedb might help, since this is just a file indexer and is not even required for installing Gitorious... @karameloso just used to find the passenger-install-apache2-module location.

Have any of you tried to re-run chef-solo after this failure? Sometimes, there may be a network problem or other kind of problem that just re-running chef-solo would finish the installation...

**Comment by benjaminmateev** [comment]
I tried executing chef-solo multiple times. Because it executes just the things that are not on the system anyway. But it didn't help. Really strange, that it cannot execute that command.

**Comment by andreaswolf** [comment]
You have to add `/var/lib/gems.../bin`  to your `$PATH` for this to work. Unfortunately, Debian resets `$PATH` to a specified value by default - for security reasons, which sounds reasonable. This however makes the scripts fail...

**Comment by rosenfeld** [comment]
Ah, ok, now I know what went wrong and I'm able to close this ticket. I didn't notice before that the gems were being installed in /var/lib/gems... If you follow the instructions in README, you should install RubyGems manually because Gitorious won't currently work with any RubyGems version.

So, I'm closing this as invalid. Just follow the README instructions.

**Comment by rosenfeld** [comment]
@andreaswolf, thanks by the way! :)
