### ISSUE TITLE
Upgrade process

### ISSUE THREAD

**Issue by eithe** [rosenfeld/gitorious-cookbooks#8]
Hi there!

First of all, thanks for creating this!

How would you go about upgrading to a newer gitorious version after installing using this method?

**Comment by rosenfeld** [comment]
Maybe I didn't state it in the README (should do), but currently this recipe doesn't support upgrade. It would be too much work for me to maintain this feature alone, so I prefer to keep the recipe simpler.

You should use this recipe just as a start base. For upgrading, you should do the normal Rails upgrade tasks. Pull last changes, run the migrations, restart the server. Now that Gitorious became versioned, there should be some upgrade instructions in Gitorious wiki.

I would recommend you to subscribe to Gitorious mailing list and ask help there.

**Comment by eithe** [comment]
Thanks.
