### ISSUE TITLE
Chef::Exceptions::ValidationFailed: Option name's value (none) does not match regular expression /^[\-[:alnum:]_:.]+$/

### ISSUE THREAD

**Issue by bshanks** [rosenfeld/gitorious-cookbooks#9]
# chef-solo

[Mon, 15 Aug 2011 20:27:54 -0400] INFO: **\* Chef 0.10.4 ***
[Mon, 15 Aug 2011 20:27:57 -0400] FATAL: Stacktrace dumped to /root/chef-solo/chef-stacktrace.out
[Mon, 15 Aug 2011 20:27:57 -0400] FATAL: Chef::Exceptions::ValidationFailed: Option name's value (none) does not match regular expression /^[-[:alnum:]_:.]+$/

**Comment by bshanks** [comment]
Generated at Mon Aug 15 20:34:40 -0400 2011
Chef::Exceptions::ValidationFailed: Option name's value (none) does not match regular expression /^[-[:alnum:]_:.]+$/
/var/lib/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/mixin/params_validate.rb:196:in `_pv_regex'
/var/lib/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/mixin/params_validate.rb:69:in`send'
/var/lib/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/mixin/params_validate.rb:69:in `validate'
/var/lib/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/mixin/params_validate.rb:66:in`each'
/var/lib/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/mixin/params_validate.rb:66:in `validate'
/var/lib/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/mixin/params_validate.rb:56:in`each'
/var/lib/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/mixin/params_validate.rb:56:in `validate'
/var/lib/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/node.rb:217:in`name'
/var/lib/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/node.rb:596:in `build'
/var/lib/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/client.rb:232:in`build_node'
/var/lib/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/client.rb:151:in `run'
/var/lib/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/application/solo.rb:192:in`run_application'
/var/lib/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/application/solo.rb:183:in `loop'
/var/lib/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/application/solo.rb:183:in`run_application'
/var/lib/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/application.rb:67:in `run'
/var/lib/gems/1.8/gems/chef-0.10.4/bin/chef-solo:25
/usr/local/bin/chef-solo:19:in`load'
/usr/local/bin/chef-solo:19
/root/chef-solo/chef-stacktrace.out (END)

**Comment by bshanks** [comment]
the problem was that `hostname` was (none)

this solved the problem:

hostname localhost

**Comment by rosenfeld** [comment]
Depending on what hostname you're talking about, it shouldn't be localhost for Gitorious to work. That's why by default it is "gitorious.local" in the node.json example. Just create an alias for it in /etc/hosts if you don't have a FQDN, but I guess just "localhost" won't work with Gitorious...
